#!/bin/bash
# Complete restart procedure

echo "🛑 Stopping all servers..."
pkill -9 -f mini2_server
sleep 2

echo ""
echo "✅ All servers stopped"
echo ""
echo "================================================================"
echo "NOW START ALL 6 SERVERS AGAIN (in separate terminals):"
echo "================================================================"
echo ""
echo "Terminal 1: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh A"
echo "Terminal 2: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh B"
echo "Terminal 3: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh C"
echo "Terminal 4: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh D"
echo "Terminal 5: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh E"
echo "Terminal 6: cd /Users/spartan/Desktop/CMPE275/mini_2 && ./scripts/start_node.sh F"
echo ""
echo "================================================================"
echo "AFTER ALL 6 ARE STARTED, you should see NEW messages:"
echo "================================================================"
echo ""
echo "Process A should show:"
echo "  [RequestProcessor] Initialized for node A"
echo "  [RequestProcessor] Connected to team leader: localhost:50051"
echo "  [RequestProcessor] Connected to team leader: localhost:50054"
echo "  [Setup] Node A configured as Leader with team leader connections"
echo ""
echo "Process B should show:"
echo "  [RequestProcessor] Initialized for node B"
echo "  [RequestProcessor] Connected to leader: localhost:50050"
echo "  [Setup] Node B configured as Team Leader"
echo ""
echo "Then test with:"
echo "  ./scripts/quick_test.sh"
echo ""
